import Head from 'next/head';
import {useRouter} from 'next/router';
import Image from 'next/image';
import {useEffect} from 'react';
import {useAppSelector, useAppDispatch} from 'store';
import {musicsearchAsync} from 'store/api/features/musicsearchSlice';

function MusicSearch() {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const {musicSearchResult} = useAppSelector((state: any) => state.musicsearch);

  console.log(musicSearchResult, '결과');

  const songIds = musicSearchResult.songId;

  const gotoMusic = (songIds: number) => {
    router.push(`/music/${songIds}`);
  };

  useEffect(() => {
    console.log(musicSearchResult, '결과');
    // dispatch(musicsearchAsync(title))
  }, [musicSearchResult]);

  return (
    <>
      <Head>
        <title>MusicSearch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <main className="flex flex-row min-h-[91vh] bg-gradient-to-t from-slate-700 to-slate-900 ">
        <div className="flex flex-row justify-center w-[88%] ml-[12%]">
          {/* 서치 리스트 랜더링 */}
          <div className="flex flex-row flex-wrap text-white">
            {Array.isArray(musicSearchResult) &&
              musicSearchResult.map((item, songId) => (
                <div
                  className="flex flex-col items-center bg-blue-400 border-2 m-3 w-[200px]"
                  key={songId}
                  // onClick={}
                >
                  {/* <div>{item.songId}</div> */}
                  <img
                    className="w-[100px]"
                    src={item.albumImgPath}
                    alt="albumimage"
                  />
                  <div className="text-md">{item.title}</div>
                  <div>{item.artist}</div>
                  {/* <p>{item.}</p> */}
                </div>
              ))}
          </div>
        </div>
      </main>
    </>
  );
}

export default MusicSearch;
