import Head from 'next/head';
import {useRouter} from 'next/router';
import Image from 'next/image';
import {useEffect} from 'react';

function MusicSearch() {
  const router = useRouter();
  const {keyword} = router.query;

  useEffect(() => {
    console.log(keyword);
  }, [keyword]);

  return (
    <>
      <Head>
        <title>MusicSearch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <main className="flex flex-col min-h-[91vh] bg-gradient-to-t from-slate-700 to-slate-900">
        <div className=" flex flex-row justify-center w-[88%] h-[840px] ml-[12%]">
          <h1 className="text-6xl font-bold">Search Result</h1>
        </div>
      </main>
    </>
  );
}

export default MusicSearch;
