import Head from 'next/head';
import {useRouter} from 'next/router';

function Musicplayer() {
  const MusicData = {
    // 임시 데이터
    musicTitle: '호랑 나비',
    artistName: '김흥국',
    artistImage:
      'https://cdnimg.melon.co.kr/cm/artistcrop/images/000/01/194/1194_500.jpg?4867e82abe04463f1dd41663eba70eb4/melon/resize/416/quality/80/optimize',
    albumName: 'Kim Heung Kook',
    albumImage:
      'https://cdnimg.melon.co.kr/cm/album/images/003/11/964/311964_500.jpg',
    releaseYear: '1989',
    musicUrl: 'avHH4syRR-A'
  };

  return (
    <div>
      <Head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col min-h-[91vh] bg-gradient-to-t from-slate-700 to-slate-900 justify-center">
        <div
          className="w-[1690px] h-[830px] ml-[230px]"
          style={{
            backgroundImage: `url(${MusicData.albumImage})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            opacity: '0.3'
          }}></div>
        <div className="absolute flex flex-row left-[30%] bg-red-400">
          <img
            className="w-[300px] h-[300px] rounded-lg border-2 md:w-[350px] md:h-[350px]"
            src={MusicData.albumImage}
            alt="album_image"
          />
        </div>
      </main>
    </div>
  );
}

export default Musicplayer;
