import Head from 'next/head';

function MusicList() {
  return (
    <>
      <Head>
        <title>MusicList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>

      <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-red-400">
        <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
          <h1 className="text-6xl font-bold"></h1>
        </main>
      </div>
    </>
  );
}
