"""empty message

Revision ID: 4572e04098a9
Revises: 
Create Date: 2023-03-30 14:53:02.423610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4572e04098a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_table_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_table_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['test_table_id'], ['test_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table_2')
    op.drop_table('tt')
    op.drop_table('test_table')
    # ### end Alembic commands ###
